import { getISOWeek } from 'date-fns'

// Banco di frasi pre-scritte per lo Stato forma (currentForm/TSB) — nessuna
// chiamata AI. Stesso meccanismo di lib/recoveryPhrases.ts (rotazione
// settimanale), ma contenuto distinto: qui il racconto è sul bilancio
// carico-cronico/fatica-acuta (direzione dell'allenamento nel tempo), non sulla
// prontezza del singolo giorno come per il Recovery Score.
export const FORMA_PHRASES: Record<string, string[]> = {
  'In Slancio': [
    'Il carico cronico è ben al di sopra della fatica recente — hai margine per uno sforzo importante.',
    'Settimane di lavoro si sono trasformate in riserva: oggi puoi attingerci.',
    'Stato di forma ottimale: la base costruita nelle ultime settimane è pronta per essere usata.',
    'Sei nella fase in cui il lavoro fatto prima paga adesso.',
    'Fresco: il divario tra fitness accumulata e fatica recente lavora a tuo favore.',
    'Il momento in cui conviene incassare il lavoro fatto con un\'uscita importante.',
    'Stato di forma fresco — la base è solida, il conto con la fatica è in attivo.',
    'Hai costruito riserva sufficiente per affrontare qualcosa fuori dalla norma.',
    'Il bilancio tra carico cronico e fatica acuta non potrebbe essere più favorevole.',
    'Fresco: è il momento di trasformare mesi di allenamento in un risultato concreto.',
    'La tua base di fondo è più alta della fatica del momento — sfruttala.',
    'Stato ottimale: il lavoro di fondo ha creato margine reale, non solo sulla carta.',
    'Sei nella finestra in cui il corpo può rendere più di quanto normalmente farebbe.',
    'Fresco e pronto: la fatica recente non intacca la base costruita nel tempo.',
    'Il momento migliore per un obiettivo a lungo termine che stai coltivando da mesi.',
    'Stato di forma fresco — raro restare qui a lungo, vale la pena approfittarne.',
    'Il carico cronico costruito finora è la tua riserva più preziosa: usala ora.',
    'Sei in vantaggio sul tuo stesso allenamento — il momento giusto per un test serio.',
    'Fresco: la base è ampia, la fatica recente è marginale in confronto.',
    'Stato ideale per mettere alla prova mesi di costanza in un\'unica uscita.',
    'Il bilancio gioca a tuo favore in modo netto — è la finestra da non perdere.',
    'Sei pronto a livello di fondo, non solo di forma del momento.',
    'Fresco: il lavoro fatto in passato si sta finalmente traducendo in margine reale.',
    'Stato di forma che ripaga la costanza — il momento di raccoglierne i frutti.',
    'Il divario tra fitness e fatica è ampio: oggi puoi permetterti l\'eccezione.',
  ],
  'In Crescita': [
    'Buon equilibrio tra carico cronico e fatica recente — margine per un impegno concreto.',
    'Stato solido: la base costruita regge bene rispetto allo sforzo recente.',
    'In forma: il lavoro di fondo sta dando i suoi frutti senza eccessi di fatica.',
    'Un buon momento per consolidare quanto costruito con un\'uscita di peso.',
    'Il bilancio tra fitness e fatica è a tuo favore, senza essere eccezionale.',
    'Stato di forma buono — margine sufficiente per non doverti risparmiare.',
    'In forma: la costanza recente si sta traducendo in una base solida.',
    'Il carico cronico regge bene, la fatica acuta resta sotto controllo.',
    'Buon momento per un\'uscita che richieda più del solito impegno.',
    'Stato favorevole: puoi contare sulla base costruita nelle ultime settimane.',
    'In forma: né al tuo picco né in affanno, un solido punto intermedio.',
    'Il lavoro recente ha costruito margine reale, sfruttabile senza rischi eccessivi.',
    'Stato di forma buono — utile per consolidare un obiettivo a medio termine.',
    'In forma: il bilancio premia chi ha lavorato con costanza nelle ultime settimane.',
    'Buon equilibrio generale — margine per un\'uscita oltre la routine abituale.',
    'Stato solido: la base regge, la fatica non ha ancora eroso il vantaggio.',
    'In forma: puoi permetterti di alzare il livello senza esporti troppo.',
    'Il carico accumulato si sta trasformando in una base affidabile.',
    'Buon momento per un test di media entità sulla tua forma attuale.',
    'Stato favorevole: la costanza recente comincia a dare risultati tangibili.',
    'In forma: il margine c\'è, va usato con intenzione, non sprecato.',
    'Il bilancio tra fondo e fatica è solido — buona base per un impegno reale.',
    'Stato di forma buono — il momento per consolidare più che per stupire.',
    'In forma: la base costruita nelle ultime settimane sostiene bene lo sforzo.',
    'Buon equilibrio: puoi spendere parte del margine accumulato con fiducia.',
  ],
  'In Equilibrio': [
    'Carico bilanciato: la forma attuale sostiene il ritmo che stai già tenendo.',
    'Stato neutro: né in costruzione né in affanno, un buon equilibrio di base.',
    'Il bilancio tra fondo e fatica è nella norma — mantieni il passo attuale.',
    'Neutro: la costanza conta più di qualsiasi spinta improvvisa oggi.',
    'Stato di forma bilanciato — utile per proseguire senza cambiare programma.',
    'Il carico cronico e quello acuto si equivalgono: nessun segnale forte.',
    'Neutro: buon momento per consolidare piuttosto che rincorrere un salto di livello.',
    'Stato nella media — la regolarità paga più di un\'uscita fuori scala oggi.',
    'Il bilancio è stabile: continua con quello che stai già facendo bene.',
    'Neutro: né margine da sfruttare né fatica da temere in modo particolare.',
    'Stato di forma equilibrato — il momento giusto per la routine, non per l\'eccezione.',
    'Il carico recente non sta né costruendo né erodendo la base in modo netto.',
    'Neutro: la forma regge il ritmo attuale, senza slanci particolari.',
    'Stato bilanciato — utile più per la tenuta nel tempo che per un exploit.',
    'Il bilancio tra fondo e fatica resta stabile da un po\': segno di costanza.',
    'Neutro: continuare con lo stesso passo è la scelta più sensata oggi.',
    'Stato di forma nella norma — nessuna urgenza di cambiare direzione.',
    'Il carico cronico regge, quello acuto non preoccupa: equilibrio ordinario.',
    'Neutro: il momento in cui la costanza conta più della singola prestazione.',
    'Stato stabile — buona occasione per un\'uscita di mantenimento della base.',
    'Il bilancio nella media riflette settimane senza grossi sbalzi di carico.',
    'Neutro: né da spingere né da tirare il freno, il ritmo attuale funziona.',
    'Stato di forma equilibrato — la regolarità resta la strategia migliore.',
    'Il carico attuale sostiene la base senza intaccarla né rinforzarla molto.',
    'Neutro: un buon momento per proseguire con metodo, senza forzare la mano.',
  ],
  'In Calo': [
    'La fatica recente ha superato la base costruita — considera un giorno di recupero.',
    'Stato di forma affaticato: il carico acuto pesa più del fondo attuale.',
    'Il bilancio tra fitness e fatica pende verso la fatica — meglio moderare.',
    'Affaticato: le ultime settimane hanno chiesto più di quanto la base reggesse comoda.',
    'Stato che chiede un recupero mirato prima di aggiungere altro carico.',
    'Il carico acuto ha superato quello cronico: segnale da non ignorare.',
    'Affaticato: la base c\'è, ma la fatica recente la sta erodendo.',
    'Stato di forma in affanno — un rallentamento oggi protegge la base costruita.',
    'Il bilancio segnala che hai spinto più della tua base attuale in questo momento.',
    'Affaticato: meglio consolidare il recupero che aggiungere altro sforzo.',
    'Stato che richiede attenzione: il carico recente supera la capacità di assorbirlo.',
    'Il fondo costruito nelle settimane precedenti sta assorbendo un colpo.',
    'Affaticato: la fatica acuta ha temporaneamente il sopravvento sulla base.',
    'Stato di forma in calo — un paio di giorni più leggeri riequilibrerebbero le cose.',
    'Il bilancio pende verso la fatica: non è il momento di alzare il carico.',
    'Affaticato: la base regge, ma sta lavorando sotto sforzo più del normale.',
    'Stato che segnala di aver spinto oltre la propria base recente.',
    'Il carico acuto sta erodendo il margine costruito nelle settimane precedenti.',
    'Affaticato: vale la pena rallentare prima che il segnale diventi più netto.',
    'Stato di forma in affanno — la base resta, ma va protetta ora.',
    'Il bilancio richiede un aggiustamento: meno carico, più recupero nei prossimi giorni.',
    'Affaticato: le uscite ravvicinate stanno chiedendo il conto alla base.',
    'Stato che invita a consolidare invece che continuare a spingere.',
    'Il fondo costruito rischia di essere intaccato se il carico continua così.',
    'Affaticato: il momento di dare respiro alla base prima di richiederle altro.',
  ],
  'In Debito': [
    'Il carico acuto ha superato di molto la base costruita — serve un recupero vero.',
    'Stato di forma in sovraccarico: la fatica ha preso il sopravvento sul fondo.',
    'Il bilancio è compromesso: continuare così rischia di intaccare la base a lungo termine.',
    'Sovraccarico: le ultime settimane hanno chiesto più di quanto la base potesse reggere.',
    'Stato che segnala un rischio concreto se il carico non si riduce a breve.',
    'Il fondo costruito nel tempo sta pagando un conto salato alla fatica recente.',
    'Sovraccarico: il momento di fermarsi prima che la base ne risenta seriamente.',
    'Stato di forma critico — il recupero ora vale più di qualsiasi altra uscita.',
    'Il bilancio tra fitness e fatica è nettamente sbilanciato: priorità al riposo.',
    'Sovraccarico: continuare a questo ritmo rischia di vanificare mesi di lavoro.',
    'Stato che richiede una pausa strutturale, non solo un giorno più leggero.',
    'Il carico acuto ha superato la base in modo da non poter essere ignorato.',
    'Sovraccarico: la fatica accumulata sta erodendo quello che hai costruito finora.',
    'Stato di forma in allarme — il fondo rischia di pagare a lungo termine.',
    'Il bilancio richiede un intervento deciso: recupero prima di tutto il resto.',
    'Sovraccarico: il momento in cui proteggere la base conta più di ogni obiettivo a breve.',
    'Stato critico — le ultime settimane hanno chiesto un prezzo che ora si vede.',
    'Il fondo costruito con costanza rischia di incrinarsi se il carico non cala.',
    'Sovraccarico: rimandare un obiettivo ora protegge quelli futuri.',
    'Stato di forma compromesso — la priorità assoluta è il recupero, non il chilometraggio.',
    'Il bilancio è sbilanciato in modo netto: il momento di fermarsi è adesso.',
    'Sovraccarico: la base costruita nel tempo merita più rispetto del carico di oggi.',
    'Stato che chiede un cambio di rotta immediato, non un semplice rallentamento.',
    'Il carico ha superato una soglia che, se ignorata, si ripaga con settimane di stop.',
    'Sovraccarico: la pausa di oggi è quella che salva il lavoro di mesi.',
  ],
}

export function pickFormaPhrase(label: string, fallback: string, date: Date = new Date()): string {
  const bank = FORMA_PHRASES[label]
  if (!bank || bank.length === 0) return fallback
  return bank[getISOWeek(date) % bank.length]
}
