import { getISOWeek } from 'date-fns'

// Banco di frasi pre-scritte per fascia di Recovery Score — nessuna chiamata AI.
// Ruota settimanalmente, non giornalmente: un escursionista non genera nuovi dati
// ogni giorno, quindi non ha senso cambiare frase più spesso di quanto i dati
// stessi cambino. Tutte e 5 le fasce di computeRecoveryScore sono popolate; il
// campo `suggestion` già calcolato resta comunque il fallback per una fascia
// futura non censita qui.
export const RECOVERY_PHRASES: Record<string, string[]> = {
  Eccellente: [
    'Sei al massimo della tua forma attuale — è il momento per il percorso che rimandi da tempo.',
    'Tutto il carico recente si è trasformato in energia disponibile. Usala.',
    'Condizione ottimale: oggi nessun sentiero è troppo ambizioso.',
    'Sei fresco quanto basta per non porti limiti.',
    'Il corpo è pronto a spingere oltre la solita misura.',
    'Forma eccellente — è il tipo di giorno che ricorderai per aver osato di più.',
    'Nessun segno di fatica residua: hai margine per il percorso più duro della lista.',
    'Sei nel punto più alto del tuo equilibrio attuale tra sforzo e recupero.',
    'Se hai una vetta ambiziosa in mente, oggi è la giornata giusta per tentarla.',
    'Il recupero è stato talmente efficace da lasciarti pronto per qualsiasi cosa.',
    'Stato ottimale: puoi permetterti un dislivello importante senza pensarci due volte.',
    'Difficile trovare un momento migliore per il sentiero che ti spaventa un po\'.',
    'Eccellente: la fatica accumulata è un ricordo lontano.',
    'Sei in una condizione che capita raramente — vale la pena sfruttarla.',
    'Pieno di energia residua: oggi puoi permetterti di esagerare, con criterio.',
    'Il tuo corpo ti sta dando il via libera — approfittane.',
    'Forma al top: è il momento di alzare l\'asticella, non di accontentarti.',
    'Nessun freno oggi: il recupero ha fatto il suo lavoro alla perfezione.',
    'Ti trovi in una condizione ideale per mettere alla prova i tuoi limiti attuali.',
    'Il bilancio tra sforzo e riposo non potrebbe essere più a tuo favore.',
    'Sei pronto per il tipo di giornata che ridefinisce cosa consideri "impegnativo".',
    'Stato di forma eccellente — un\'occasione da non sprecare su un\'uscita qualunque.',
    'Hai tutta l\'energia per affrontare un percorso fuori dalla tua comfort zone.',
    'Il momento migliore per il progetto ambizioso che tieni in un cassetto.',
    'Eccellente equilibrio: oggi il limite lo scegli tu, non la fatica.',
  ],
  Buono: [
    'Buon equilibrio tra sforzo e riposo — hai margine per un\'uscita di slancio.',
    'Sei in un momento solido: nulla ti trattiene da una tappa più impegnativa.',
    'Il corpo ha smaltito bene il carico recente. Puoi permetterti di spingere un po\'.',
    'Stai bene: non al massimo, ma abbastanza per un percorso con qualche dislivello in più.',
    'Recupero solido. Se hai un sentiero in mente da un po\', questo è un buon momento.',
    'Ti sei ripreso bene dalle uscite recenti — margine per qualcosa di più lungo.',
    'Un equilibrio che regge: puoi scegliere un percorso più esigente senza rischiare troppo.',
    'Sei fresco a sufficienza per non doverti risparmiare, ma senza esagerare.',
    'Buona base — il tipo di momento in cui un sentiero nuovo vale la candela.',
    'Ti reggi bene sulle gambe: hai margine, anche se non sei al tuo picco.',
    'Recovery buono: la fatica accumulata resta sotto controllo.',
    'Discreto respiro tra sforzo e recupero — puoi alzare un po\' l\'asticella.',
    'Non sei scarico: c\'è margine per una salita che normalmente eviteresti.',
    'Bilancio positivo tra carico e riposo. Buon momento per qualcosa di più ambizioso.',
    'Recovery solido: abbastanza per un\'uscita che richieda un po\' di impegno in più.',
    'Il carico recente non ha lasciato strascichi — buon momento per alzare il livello.',
    'Sei in una fase favorevole: il corpo risponde bene a uno sforzo maggiore.',
    'Buon margine di recupero — utile per il percorso che di solito rimandi.',
    'Stato positivo: non il tuo picco assoluto, ma abbastanza per non tirartene indietro.',
    'Il bilancio pende verso il recupero — oggi puoi permetterti qualcosa in più.',
    'Recovery buono: un buon momento per testare un dislivello superiore al solito.',
    'Ti sei ripreso meglio della media recente — vale la pena sfruttarlo.',
    'Condizione solida: il tipo di giorno in cui conviene osare un po\' di più.',
    'Buon equilibrio generale — margine sufficiente per un\'uscita più lunga del previsto.',
    'Recupero efficace: il corpo è pronto per qualcosa oltre la routine.',
  ],
  Neutro: [
    'Equilibrio nella norma: né scarico né al massimo, il classico giorno da mantenere il ritmo.',
    'Carico e recupero si bilanciano — nulla che richieda un cambio di programma.',
    'Stato neutro: va bene continuare come stai facendo, senza strafare né tirare il freno.',
    'Non c\'è un segnale forte in una direzione o nell\'altra — giornata da "solito passo".',
    'Recovery nella media: un\'uscita normale è la scelta più sensata.',
    'Ti trovi in una zona stabile — buon momento per consolidare, non per spingere oltre.',
    'Equilibrio ordinario: il tipo di giorno in cui la routine funziona meglio delle scommesse.',
    'Né fatica né slancio particolare — resta sul percorso che conosci bene.',
    'Stato intermedio: puoi allenarti, ma senza cercare il record personale oggi.',
    'Il bilancio è nella media — buona occasione per un\'uscita di mantenimento.',
    'Nessun estremo: oggi è più un giorno da consolidare abitudini che da osare.',
    'Equilibrio neutro: valido per continuare quello che stai già facendo bene.',
    'Ritmo sostenibile — non serve cambiare nulla, solo continuare con costanza.',
    'Nella media: né un giorno da riposo forzato né uno da spingere al massimo.',
    'Stato bilanciato — il momento giusto per un\'uscita onesta, senza sorprese.',
    'Carico gestito bene finora: continua così, senza forzare la mano.',
    'Equilibrio nella norma — utile più per la costanza che per le imprese.',
    'Nessun segnale d\'allarme, ma nemmeno di slancio: giornata da ritmo abituale.',
    'Ti trovi in una fase di consolidamento — non il momento per strafare.',
    'Stato intermedio tra fatica e freschezza — la scelta prudente è il tuo standard.',
    'Il bilancio attuale premia la regolarità più che l\'azzardo.',
    'Recovery nella media: va bene un\'uscita, meno bene un\'impresa.',
    'Equilibrio ordinario — il classico giorno in cui "va bene così" è la risposta giusta.',
    'Nessuna urgenza né di spingere né di fermarti: prosegui al tuo ritmo.',
    'Stato neutro: il momento ideale per un\'uscita che consolida, non che stupisce.',
  ],
  Affaticato: [
    'La fatica si sta accumulando — un\'uscita più leggera oggi paga domani.',
    'Il carico recente pesa più del solito: meglio non spingere ulteriormente.',
    'Stato di affaticamento: il corpo chiede una tregua, anche breve.',
    'Non è il momento per il percorso più duro della lista — meglio rimandarlo.',
    'Qualche segnale di stanchezza in più del previsto — vale la pena ascoltarlo.',
    'Il recupero non ha ancora tenuto il passo con lo sforzo recente.',
    'Affaticamento in aumento: un\'uscita breve o un giorno di riposo aiuterebbero.',
    'Il bilancio pende verso la fatica — oggi conviene essere prudenti.',
    'Stai accumulando più carico di quanto il corpo stia smaltendo.',
    'Un segnale da non ignorare: la fatica residua è più alta della norma.',
    'Meglio un\'uscita facile oggi che un infortunio la prossima settimana.',
    'Il corpo sta chiedendo di rallentare, anche se la testa vorrebbe il contrario.',
    'Affaticamento moderato — non è un\'emergenza, ma nemmeno da ignorare.',
    'Il carico accumulato inizia a farsi sentire — un recupero mirato aiuterebbe.',
    'Stato di stanchezza: oggi il sentiero più prudente è anche il più intelligente.',
    'Vale la pena investire in riposo prima di aggiungere altro carico.',
    'Il segnale è chiaro: fatica in aumento, margine in diminuzione.',
    'Non è il giorno per testare i tuoi limiti — lo saranno altri.',
    'Affaticamento: la costanza paga di più della spinta in più oggi.',
    'Il corpo sta lavorando più duramente del solito solo per recuperare.',
    'Meglio ridurre l\'intensità oggi che perdere una settimana intera dopo.',
    'Stato di fatica accumulata — un passo indietro ora ne vale diversi avanti.',
    'Il bilancio segnala che il recupero ha bisogno di più tempo del previsto.',
    'Non forzare: la fatica di oggi è il prezzo di qualche uscita ravvicinata.',
    'Affaticamento in crescita — questo è il momento di dare priorità al riposo.',
  ],
  Sovraccarico: [
    'Il carico ha superato quello che il corpo riesce a smaltire — serve una pausa vera.',
    'Sovraccarico: oggi il riposo è più utile di qualsiasi uscita.',
    'Il segnale è netto: la fatica accumulata chiede una tregua, non un\'altra spinta.',
    'Stato di sovraccarico — è il momento di ascoltare il corpo, non l\'agenda.',
    'Il bilancio è sbilanciato verso la fatica in modo significativo: fermarsi conviene.',
    'Meglio saltare l\'uscita di oggi che rischiare di doverne saltare molte di più.',
    'Il recupero è rimasto indietro rispetto al carico per troppo tempo.',
    'Sovraccarico evidente: un giorno di riposo oggi previene settimane di stop forzato.',
    'Il corpo sta segnalando un limite superato — vale la pena prenderlo sul serio.',
    'Non è prudenza eccessiva: è quello che i dati stanno effettivamente dicendo.',
    'Stato di affaticamento marcato — oggi la scelta migliore è non fare nulla.',
    'Il carico accumulato ha superato la capacità di recupero attuale.',
    'Sovraccarico: il momento di fermarsi prima che sia il corpo a farlo per te.',
    'Il segnale è forte abbastanza da meritare una pausa, non solo un\'uscita più leggera.',
    'Fatica elevata su più fronti — il riposo oggi è un investimento, non una rinuncia.',
    'Stato critico di affaticamento: rimandare l\'uscita è la scelta più sensata.',
    'Il corpo ha bisogno di più tempo di quanto gli hai dato finora.',
    'Sovraccarico: continuare adesso rischia di costare più di quanto guadagni.',
    'Il bilancio è compromesso — priorità assoluta al recupero, non al chilometraggio.',
    'Meglio un riposo completo oggi che un infortunio che ti ferma per settimane.',
    'Stato di sovraccarico: il momento in cui "niente" è la risposta più allenante.',
    'Il carico ha superato una soglia che vale la pena rispettare, non forzare.',
    'Fatica accumulata oltre la norma — oggi il corpo chiede tregua, non compromessi.',
    'Sovraccarico marcato: la pausa di oggi è quello che ti permette di tornare più forte.',
    'Il segnale non lascia margini di interpretazione: serve riposo, non un\'altra uscita.',
  ],
}

export function pickRecoveryPhrase(label: string, fallback: string, date: Date = new Date()): string {
  const bank = RECOVERY_PHRASES[label]
  if (!bank || bank.length === 0) return fallback
  return bank[getISOWeek(date) % bank.length]
}
