import { getISOWeek } from 'date-fns'

// Banco di frasi pre-scritte per lo Streak (settimane consecutive con almeno
// un'uscita, streaks.currentWeeks — vedi lib/stats.ts). A differenza di
// Recovery/Stato forma non ci sono fasce nominate: i bucket seguono le stesse
// soglie già usate dai badge streak_4w/streak_8w/streak_26w in lib/badges.ts,
// così il tono cambia negli stessi punti in cui cambia anche un traguardo.
const BUCKETS = ['0', '1-3', '4-7', '8-25', '26+'] as const
type Bucket = typeof BUCKETS[number]

export function streakBucket(weeks: number): Bucket {
  if (weeks <= 0) return '0'
  if (weeks <= 3) return '1-3'
  if (weeks <= 7) return '4-7'
  if (weeks <= 25) return '8-25'
  return '26+'
}

export const STREAK_PHRASES: Record<Bucket, string[]> = {
  '0': [
    'Nessuna settimana attiva al momento — ripartire non richiede altro che un\'uscita.',
    'Lo streak è a zero, ma basta un\'uscita per farlo ripartire.',
    'Non c\'è una serie in corso: il prossimo passo è anche il primo di una nuova.',
    'Zero settimane consecutive — nessun dramma, solo un punto di partenza.',
    'Lo streak riparte da qui: basta una sola uscita per rimetterlo in moto.',
    'Nessuna striscia attiva, ma nemmeno un obbligo di recuperarla in fretta.',
    'Il contatore è a zero — utile solo come punto da cui ripartire, non da cui giudicarsi.',
    'Nessuna settimana consecutiva ora: la prossima uscita è già l\'inizio di una nuova serie.',
    'Streak a zero — capita, e non pesa più di quanto tu voglia farlo pesare.',
    'Non c\'è una serie da difendere in questo momento: solo la libertà di ricominciare.',
    'Zero settimane di fila — il modo più semplice per ripartire è la prossima uscita.',
    'Lo streak si è interrotto, ma il prossimo inizio non richiede recuperare nulla.',
    'Nessuna continuità al momento: un buon momento per deciderne una nuova, senza fretta.',
    'Il contatore è fermo a zero — non è un giudizio, solo uno stato di partenza.',
    'Streak assente: la prossima settimana con un\'uscita lo rimette subito in moto.',
    'Nessuna serie attiva — meno pressione, più libertà di scegliere quando ripartire.',
    'Zero al momento: quello che conta da qui è la prossima uscita, non quelle mancate.',
    'Lo streak riparte sempre dalla prossima uscita, mai da quelle perse.',
    'Nessuna continuità ora — è un dato, non un voto sulla costanza generale.',
    'Streak a zero: il momento più semplice per ricominciare è adesso, senza fretta di recuperare.',
    'Il contatore fermo non racconta tutta la storia — solo l\'ultima settimana.',
    'Nessuna serie in corso: utile pensarla come una lavagna pulita, non come un debito.',
    'Zero settimane di fila — la prossima uscita conta quanto la prima di sempre.',
    'Streak interrotto: non serve recuperare il tempo perso, solo ripartire con calma.',
    'Nessuna continuità attiva — un buon momento per scegliere la prossima uscita con calma.',
  ],
  '1-3': [
    'Le prime settimane di una serie — il momento in cui l\'abitudine comincia a prendere forma.',
    'Streak agli inizi: poche settimane, ma è da qui che nascono le abitudini solide.',
    'Una piccola serie in corso — vale la pena alimentarla con la prossima uscita.',
    'Le basi di una regolarità nuova si stanno posando, settimana dopo settimana.',
    'Streak giovane: ogni settimana in più adesso conta doppio per l\'abitudine.',
    'Sei all\'inizio di una serie — il momento in cui si decide se diventa costanza.',
    'Poche settimane di fila, ma è il tratto in cui un\'abitudine si consolida o si perde.',
    'Streak in costruzione: continuare ora vale più che accelerare più avanti.',
    'Le prime settimane sono le più fragili — e anche le più decisive per l\'abitudine.',
    'Una serie che sta prendendo forma — bastano poche uscite in più per renderla solida.',
    'Streak agli inizi: il momento in cui la regolarità è ancora una scelta attiva, non un riflesso.',
    'Poche settimane consecutive, ma già un segnale di intenzione più che di caso.',
    'La serie è giovane — proteggerla ora significa non doverla ricominciare tra poco.',
    'Streak in fase iniziale: ogni settimana aggiunta consolida quelle precedenti.',
    'L\'abitudine si sta formando — le prossime settimane contano più delle prime.',
    'Una piccola striscia attiva: il momento migliore per non lasciarla cadere.',
    'Streak giovane ma reale — la costanza dei prossimi giorni la rende un\'abitudine.',
    'Poche settimane di fila: il punto in cui una serie può diventare parte della routine.',
    'La serie è ancora fragile — un\'uscita in più adesso la rende meno casuale.',
    'Streak agli inizi: il momento in cui vale la pena scegliere la costanza, non l\'intensità.',
    'Una serie appena avviata — continuarla conta più di come la inizi.',
    'Le prime settimane contano doppio: è qui che si decide se diventa abitudine.',
    'Streak in costruzione: piccoli passi ripetuti valgono più di un\'uscita isolata.',
    'Una striscia ancora corta, ma già un segnale di intenzione da non sprecare.',
    'Streak giovane: il momento in cui la regolarità inizia a diventare naturale.',
  ],
  '4-7': [
    'Un mese di fila con almeno un\'uscita — l\'abitudine ha smesso di essere un\'intenzione.',
    'Streak solido: la regolarità è diventata parte della routine, non un\'eccezione.',
    'Diverse settimane consecutive — il tipo di costanza che comincia a vedersi nei dati.',
    'L\'abitudine si è consolidata: mantenerla ora costa meno che costruirla.',
    'Streak affidabile — la continuità sta diventando la norma, non lo sforzo.',
    'Settimane di fila che iniziano a contare come una vera abitudine, non un caso.',
    'La serie ha superato la fase più fragile — ora si tratta di non interromperla per distrazione.',
    'Streak solido: il tipo di costanza che rende più facile la prossima uscita, non più difficile.',
    'Diverse settimane consecutive — un buon segnale di quanto sia diventata naturale l\'uscita regolare.',
    'L\'abitudine regge da un po\': il rischio ora è la distrazione, non la mancanza di volontà.',
    'Streak consolidato — la regolarità comincia a lavorare a tuo favore, non contro.',
    'Diverse settimane di fila: la costanza è visibile, non solo percepita.',
    'La serie ha superato il punto più delicato — ora è questione di mantenerla con meno sforzo.',
    'Streak affidabile: l\'abitudine si sta radicando, uscita dopo uscita.',
    'Diverse settimane consecutive — il tipo di continuità che rende superflua la motivazione quotidiana.',
    'L\'abitudine è diventata più solida della singola voglia di uscire o no.',
    'Streak consolidato: la costanza recente parla più di qualsiasi buon proposito.',
    'Diverse settimane di fila — un segnale concreto che la regolarità è diventata reale.',
    'La serie è abbastanza lunga da reggere anche una settimana difficile, se capita.',
    'Streak solido: mantenerlo ora è più semplice che quando è iniziato.',
    'Diverse settimane consecutive — l\'abitudine ha superato la fase di volontà pura.',
    'La costanza recente si è trasformata in qualcosa di più stabile di un buon proposito.',
    'Streak affidabile: la regolarità è ormai una caratteristica, non un\'eccezione.',
    'Diverse settimane di fila — il tipo di continuità che rende naturale la prossima uscita.',
    'L\'abitudine si è consolidata al punto da reggere anche i momenti meno motivati.',
  ],
  '8-25': [
    'Mesi di continuità — il tipo di costanza che va oltre la semplice abitudine.',
    'Streak notevole: settimane e settimane senza un\'interruzione vera.',
    'Una regolarità che dura da mesi — raro, e vale la pena riconoscerlo.',
    'La serie ha superato ampiamente la soglia dell\'abitudine casuale.',
    'Streak lungo: la continuità è ormai parte di come vivi le uscite, non un progetto.',
    'Mesi consecutivi con almeno un\'uscita — un segnale di costanza fuori dal comune.',
    'La regolarità di queste settimane racconta più di qualsiasi singola prestazione.',
    'Streak notevole: il tipo di continuità che pochi mantengono così a lungo.',
    'Mesi di fila — la costanza qui non è più merito del caso, è metodo.',
    'Una serie che dura da tempo — il segnale più chiaro di quanto sia diventata priorità.',
    'Streak lungo: mantenerlo a questo punto richiede più attenzione a piccole distrazioni che a volontà.',
    'Mesi consecutivi di uscite regolari — un risultato che raramente si nota da fuori.',
    'La continuità di queste settimane è ormai un tratto, non uno sforzo quotidiano.',
    'Streak notevole: la costanza a questo livello parla da sola.',
    'Mesi di fila senza interruzioni vere — il tipo di dato che vale la pena guardare con soddisfazione.',
    'Una regolarità che dura da tempo — raro restare così a lungo senza un\'interruzione.',
    'Streak lungo: il rischio più grande ora è dare per scontata la costanza raggiunta.',
    'Mesi consecutivi — la continuità è diventata identità, non solo comportamento.',
    'La serie ha ormai una storia alle spalle che vale la pena proteggere.',
    'Streak notevole: poche persone mantengono una regolarità così a lungo.',
    'Mesi di fila — il tipo di dato che racconta più della singola escursione migliore.',
    'Una continuità che dura da tempo merita più attenzione che celebrazione plateale.',
    'Streak lungo: a questo punto la costanza lavora da sola, quasi per inerzia buona.',
    'Mesi consecutivi di uscite — un risultato raro, costruito settimana dopo settimana.',
    'La regolarità di queste settimane è ormai la vera storia, più di ogni singola uscita.',
  ],
  '26+': [
    'Oltre sei mesi di continuità — il tipo di costanza che pochi raggiungono davvero.',
    'Streak eccezionale: mezzo anno senza un\'interruzione vera è un dato raro.',
    'Sei mesi di fila con almeno un\'uscita — la costanza qui ha superato ogni soglia comune.',
    'Una regolarità che dura da oltre sei mesi merita di essere notata, senza troppa enfasi.',
    'Streak raro: mantenerlo così a lungo dice più di qualsiasi singola prestazione.',
    'Oltre sei mesi consecutivi — il tipo di continuità che diventa parte della tua identità.',
    'Una serie di questa lunghezza racconta una storia di costanza, non di fortuna.',
    'Streak eccezionale: pochi arrivano a mantenere una regolarità così a lungo.',
    'Sei mesi di fila senza interruzioni vere — un risultato che vale la pena riconoscere con calma.',
    'Una continuità così lunga è ormai un tratto stabile, non più un progetto in corso.',
    'Streak raro: la costanza a questo livello parla da sola, senza bisogno di enfasi.',
    'Oltre sei mesi consecutivi — il tipo di dato che pochi hiker arrivano a costruire.',
    'Una serie che dura da mezzo anno merita rispetto, non solo un numero da mostrare.',
    'Streak eccezionale: mantenerlo a questo punto è più questione di identità che di sforzo.',
    'Sei mesi di fila — la continuità qui ha smesso da tempo di essere una novità.',
    'Una regolarità così lunga è rara abbastanza da meritare un momento di riconoscimento.',
    'Streak raro: il tipo di costanza che si costruisce in anni, non in settimane.',
    'Oltre sei mesi consecutivi — un risultato che parla di metodo più che di motivazione.',
    'Una serie di questa durata è ormai parte di chi sei come escursionista, non solo cosa fai.',
    'Streak eccezionale: pochi dati raccontano la costanza meglio di questo.',
    'Sei mesi di fila senza interruzioni — vale la pena fermarsi un attimo a riconoscerlo.',
    'Una continuità così rara merita di essere notata senza bisogno di gonfiarla.',
    'Streak raro: il tipo di risultato che si costruisce con pazienza, non con un colpo di fortuna.',
    'Oltre sei mesi consecutivi — la costanza qui ha superato ogni aspettativa ragionevole.',
    'Una serie di questa lunghezza è, semplicemente, un dato che parla da solo.',
  ],
}

export function pickStreakPhrase(weeks: number, date: Date = new Date()): string {
  const bank = STREAK_PHRASES[streakBucket(weeks)]
  return bank[getISOWeek(date) % bank.length]
}
