import { getISOWeek } from 'date-fns'

// Banco di frasi pre-scritte per il Volume settimanale — nessuna chiamata AI.
// Bucket per scostamento percentuale rispetto alla media delle settimane
// precedenti (non alla settimana singola, troppo rumorosa). Nessun bucket
// scatta per uno scarto minimo: solo differenze abbastanza ampie da meritare
// un commento, il resto lo dice già il numero senza bisogno di una frase.
const BUCKETS = ['molto_sotto', 'sotto', 'in_linea', 'sopra', 'molto_sopra'] as const
type Bucket = typeof BUCKETS[number]

export function volumeBucket(deltaPct: number): Bucket {
  if (deltaPct <= -40) return 'molto_sotto'
  if (deltaPct <= -15) return 'sotto'
  if (deltaPct < 15) return 'in_linea'
  if (deltaPct < 40) return 'sopra'
  return 'molto_sopra'
}

export const VOLUME_PHRASES: Record<Bucket, string[]> = {
  molto_sotto: [
    'Volume ben sotto la tua media recente — capita, e non richiede una spiegazione.',
    'Questa settimana è stata leggera rispetto al solito: nessun problema a lasciarla così.',
    'Molto meno chilometraggio del previsto — un dato, non un giudizio sulla costanza generale.',
    'Settimana sottotono rispetto alla media: succede, e la prossima riparte da zero.',
    'Volume basso questa settimana — se è una scelta, va benissimo così.',
    'Molto sotto il tuo standard recente: la settimana prossima non deve "recuperare" nulla.',
    'Una settimana leggera non cancella quelle costruite prima.',
    'Volume ridotto rispetto alla media — un dato isolato, non una tendenza per forza.',
    'Settimana sotto il solito ritmo: nessuna urgenza di compensare più del dovuto.',
    'Molto meno del tuo standard recente — la vita fuori dai sentieri conta quanto i sentieri stessi.',
    'Volume basso questa settimana: non serve inseguire i numeri della settimana scorsa.',
    'Una settimana fiacca sul chilometraggio, ma non per questo meno valida.',
    'Ben sotto la media recente — il dato racconta la settimana, non l\'abitudine.',
    'Volume ridotto: se c\'è stato poco tempo, non è un problema da correggere in fretta.',
    'Settimana leggera rispetto al solito — le medie oscillano, è normale che accada.',
    'Molto sotto lo standard recente: nessun bisogno di recuperare tutto insieme la prossima volta.',
    'Volume basso — un dato che pesa poco se guardato su un arco di mesi.',
    'Settimana sottotono: succede, e non intacca la costanza costruita finora.',
    'Ben al di sotto della media: la prossima settimana riparte senza debiti da saldare.',
    'Volume ridotto questa settimana — non tutte le settimane devono essere uguali.',
    'Molto meno chilometraggio del solito, ma senza che questo dica granché sul resto.',
    'Settimana leggera: il dato isolato conta meno della tendenza di lungo periodo.',
    'Volume basso rispetto alla media recente — non è un allarme, solo una settimana diversa.',
    'Ben sotto lo standard: va bene così, specialmente se il resto del mese regge.',
    'Settimana sottotono sul volume — nessuna necessità di giustificarla o compensarla.',
  ],
  sotto: [
    'Un po\' sotto la tua media recente — nulla di allarmante, solo una settimana più tranquilla.',
    'Volume leggermente inferiore al solito: rientra nella normale variazione.',
    'Settimana un filo sotto lo standard — capita spesso, senza che significhi granché.',
    'Qualche chilometro in meno rispetto alla media, ma nella norma.',
    'Volume moderatamente più basso del solito — parte naturale di qualsiasi routine.',
    'Settimana leggermente sottotono: il trend generale resta quello che conosci.',
    'Un po\' meno del tuo standard recente — non abbastanza da preoccuparsi.',
    'Volume in leggero calo rispetto alla media, dentro un margine normale.',
    'Settimana un po\' più leggera del solito, senza che sia un segnale da seguire.',
    'Qualche chilometro sotto la media: la classica oscillazione di ogni routine.',
    'Volume leggermente ridotto — parte fisiologica di settimane che si alternano.',
    'Un filo sotto lo standard recente, ma nulla che cambi il quadro generale.',
    'Settimana moderata sul volume — meno della media, ma dentro la norma.',
    'Volume un po\' più basso del solito: le settimane non sono mai tutte uguali.',
    'Leggermente sotto la media recente — un\'oscillazione normale, non un campanello d\'allarme.',
    'Settimana con qualche chilometro in meno, ma coerente con l\'andamento generale.',
    'Volume moderatamente sotto lo standard — la costanza si giudica su più settimane, non su una sola.',
    'Un po\' meno attivo del solito questa settimana, senza che sia un problema.',
    'Settimana leggermente sottotono — rientra tranquillamente nella variazione normale.',
    'Volume in lieve calo: il quadro generale delle ultime settimane resta solido.',
    'Qualche chilometro sotto la media recente, ma nulla fuori dall\'ordinario.',
    'Settimana un po\' più leggera — normale alternanza tra settimane più e meno intense.',
    'Volume leggermente ridotto rispetto al solito, senza impatto sul trend di fondo.',
    'Un filo sotto lo standard, ma la regolarità delle ultime settimane resta intatta.',
    'Settimana moderata sul chilometraggio — dentro la normale variazione della tua routine.',
  ],
  in_linea: [
    'Volume in linea con le ultime settimane — la costanza continua senza sorprese.',
    'Settimana nella media: lo stesso ritmo che stai tenendo da un po\'.',
    'Chilometraggio coerente con lo standard recente — nessun cambiamento particolare.',
    'In linea con la tua media: la routine sta tenendo bene il passo.',
    'Volume regolare, coerente con l\'andamento delle settimane precedenti.',
    'Settimana allineata alla media recente — la costanza continua a reggere.',
    'Nessuno scostamento significativo: il volume resta quello che conosci.',
    'In linea con lo standard delle ultime settimane, segno di una routine stabile.',
    'Volume nella norma — la regolarità recente si conferma anche questa settimana.',
    'Settimana coerente con la media: nulla che richieda un aggiustamento.',
    'Il chilometraggio segue lo stesso ritmo delle settimane precedenti.',
    'In linea con la tua media recente — la routine si mantiene stabile.',
    'Volume regolare: la settimana conferma il trend delle ultime uscite.',
    'Settimana nella media — segno che la costanza recente non è un caso isolato.',
    'Nessuno scarto rilevante dalla media: il ritmo attuale si conferma affidabile.',
    'In linea con lo standard recente, la routine continua a funzionare così com\'è.',
    'Volume coerente con le settimane precedenti — nulla da cambiare per ora.',
    'Settimana allineata alla media: la regolarità recente si consolida ulteriormente.',
    'Il chilometraggio di questa settimana conferma il ritmo che hai trovato.',
    'In linea con la media recente — la costanza continua a essere la caratteristica principale.',
    'Volume nella norma, coerente con un trend che si sta consolidando.',
    'Settimana in linea con lo standard: nessun segnale da monitorare in particolare.',
    'Il ritmo recente si conferma anche questa settimana, senza scostamenti.',
    'In linea con la media: la routine costruita nelle ultime settimane regge bene.',
    'Volume coerente — la settimana si allinea perfettamente al trend recente.',
  ],
  sopra: [
    'Volume sopra la tua media recente — un buon segnale di slancio.',
    'Settimana più intensa del solito: la costanza si sta trasformando in qualcosa in più.',
    'Chilometraggio superiore allo standard recente — margine ben sfruttato.',
    'Sopra la media: la settimana ha spinto un po\' oltre il ritmo abituale.',
    'Volume in crescita rispetto alle ultime settimane — segno di buona forma o buona volontà.',
    'Settimana sopra lo standard: hai dato qualcosa in più rispetto al solito.',
    'Il chilometraggio supera la media recente — un buon momento di spinta.',
    'Sopra la media: la costanza recente si sta traducendo in volume reale.',
    'Volume più alto del solito — vale la pena notare lo slancio di questa settimana.',
    'Settimana intensa rispetto allo standard: il trend generale sta salendo.',
    'Sopra il ritmo abituale — un segnale positivo, da non sprecare con un eccesso subito dopo.',
    'Il volume di questa settimana supera quello delle precedenti in modo netto.',
    'Sopra la media recente: buon momento, ma occhio a non esagerare la prossima.',
    'Settimana sopra lo standard — la spinta di questi giorni si vede nei numeri.',
    'Volume in aumento rispetto al trend recente: segno di buona energia disponibile.',
    'Sopra la media: la settimana ha richiesto e ottenuto qualcosa in più.',
    'Il chilometraggio supera il solito ritmo — un buon momento da consolidare, non solo da godersi.',
    'Settimana sopra lo standard recente — attenzione a bilanciarla con il recupero giusto.',
    'Volume più alto della media: segnale di slancio, utile da gestire con equilibrio.',
    'Sopra il ritmo abituale — la settimana racconta una spinta in più rispetto al solito.',
    'Il volume settimanale supera la media recente in modo evidente.',
    'Sopra lo standard: buon momento, purché non diventi la nuova norma senza recupero.',
    'Settimana sopra la media — segno che l\'energia recente si sta traducendo in chilometri.',
    'Volume in crescita: un buon segnale, da bilanciare con attenzione nelle prossime uscite.',
    'Sopra il ritmo recente — la spinta di questa settimana merita di essere notata.',
  ],
  molto_sopra: [
    'Volume ben oltre la tua media recente — la settimana più intensa da un po\'.',
    'Molto sopra lo standard: un balzo che vale la pena notare, non solo archiviare.',
    'Settimana nettamente sopra il solito ritmo — energia da gestire con attenzione ora.',
    'Il chilometraggio supera ampiamente la media delle ultime settimane.',
    'Molto più attivo del solito: un buon segnale, purché seguito da un recupero adeguato.',
    'Settimana record rispetto al trend recente — bilancia con qualche giorno più leggero.',
    'Volume nettamente sopra lo standard: la spinta di questi giorni è stata notevole.',
    'Molto sopra la media: buon momento, ma occhio a non ripeterlo senza pausa.',
    'Il chilometraggio di questa settimana ridefinisce temporaneamente il tuo standard.',
    'Settimana ben oltre il solito ritmo — un segnale di energia, non un nuovo obbligo.',
    'Volume molto alto rispetto al trend recente: goditelo, ma senza farne l\'abitudine immediata.',
    'Ben sopra lo standard: la settimana ha richiesto molto, ora tocca al recupero.',
    'Settimana nettamente più intensa del solito — un buon momento seguito da uno più calmo.',
    'Il volume supera ampiamente la media: energia ben spesa, da bilanciare ora.',
    'Molto sopra il ritmo abituale — non è detto che vada ripetuto subito.',
    'Settimana fuori scala rispetto al trend recente: un exploit, non necessariamente una nuova norma.',
    'Volume ben oltre lo standard: la prossima settimana può permettersi di essere più leggera.',
    'Molto sopra la media: la spinta è stata reale, il recupero ora è altrettanto importante.',
    'Settimana nettamente sopra il solito — vale la pena riconoscerla, senza rincorrerla subito di nuovo.',
    'Il chilometraggio ben oltre lo standard racconta una settimana fuori dall\'ordinario.',
    'Molto sopra il ritmo recente: energia importante, da alternare con giorni più tranquilli.',
    'Settimana ben oltre la media — un buon momento isolato più che un nuovo livello stabile.',
    'Volume nettamente superiore allo standard: goditi il risultato, poi lascia spazio al recupero.',
    'Molto sopra la media recente — un balzo che merita attenzione anche nel dopo.',
    'Settimana fuori scala: il dato più alto da tempo, da bilanciare con giudizio nei prossimi giorni.',
  ],
}

export function pickVolumePhrase(deltaPct: number, date: Date = new Date()): string {
  const bank = VOLUME_PHRASES[volumeBucket(deltaPct)]
  return bank[getISOWeek(date) % bank.length]
}
